
brain:

    supress_warnings: true

    allow_system_aiml: true
    allow_learn_aiml: true
    allow_learnf_aiml: true

    files:
        aiml:
            files: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/tilly/aiml
            extension: .aiml
            directories: false
        sets:
            files: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/tilly/sets
            extension: .txt
            directories: false
        maps:
            files: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/tilly/maps
            extension: .txt
            directories: false
        denormal: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/tilly/config/denormal.txt
        normal: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/tilly/config/normal.txt
        gender: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/tilly/config/gender.txt
        person: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/tilly/config/person.txt
        person2: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/tilly/config/person2.txt
        predicates: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/tilly/config/predicates.txt
        pronouns: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/tilly/config/pronouns.txt
        properties: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/tilly/config/properties.txt
        triples: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/tilly/config/triples.txt
        preprocessors: /Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/tilly/config/preprocessors.txt

bot:
    prompt: ">>>"
    default_response: Sorry, I don't have an answer for that!
    exit_response: So long, and thanks for the fish!